### ISSUE TITLE
A MELPA package?

### ISSUE THREAD

**Issue by vkazanov** [astahlman/ob-async#2]
Most Emacsers these days use `package-install`. It would be nice if `ob-async` had a package on MELPA...

**Comment by astahlman** [comment]
Good idea, I'll see if I can find time to open a PR on MELPA in the next couple of days.

**Comment by vkazanov** [comment]
Cool, thanks! That'd be great!

**Comment by astahlman** [comment]
https://github.com/melpa/melpa/pull/4568 is pending review.

**Comment by pank** [comment]
Hi,

As this is a pretty useful infrastructure feature it might make more sense to make it part of org-mode itself.  You'd need to assign copyright to FSF, though.  Here's the [relevant information](http://orgmode.org/worg/org-contribute.html).

Rasmus

**Comment by vkazanov** [comment]
@pank 

that would be awesome! 

I recently tried to automate some of my remote server tasks using org-babel and found that it's not really practical to have Emacs blocked for such a long time... ob-async feels really helpful here.

**Comment by stsquad** [comment]
There is a thread here: http://lists.gnu.org/archive/html/emacs-orgmode/2017-02/msg00348.html which would be nice to get some feedback from the org-mode maintainers on.

**Comment by astahlman** [comment]
Thanks for the link @stsquad. I'd love to see generic support for asynchronous execution in org-mode - especially if someone else were willing to drive it :wink:. Let's see what the org-mode maintainers think.

**Comment by astahlman** [comment]
`ob-async` is now available in MELPA.
