### ISSUE TITLE
RESULTS replaced before the confirmation

### ISSUE THREAD

**Issue by avkoval** [astahlman/ob-async#23]
# Checklist
- [x] I followed the [troubleshooting guide](https://github.com/astahlman/ob-async#troubleshooting) and it did not address my issue
- [ ] I've included a link to a Github Gist with the full contents of my `troubleshooting.org` buffer
- [x] Each section below is filled in and includes sufficient detail to reproduce the issue

# Expected Behavior
Consider following simple template:

~~~
#+BEGIN_SRC sh :dir ~ :results output replace :async 
echo Hello, World!
#+END_SRC
~~~

When I press C-c I get:

Evaluate this sh code block on your system? (y or n) y
and the RESULTS block is changed to:

~~~
#+RESULTS:
: 6fc00bde7e0c6b7623f6e3e05c16fbba
~~~
*after* I confirm the execution

# Actual Behavior

When I press C-c I get RESULTS block changed immediately, the answer y/n does not matter

~~~
#+RESULTS:
: 6fc00bde7e0c6b7623f6e3e05c16fbba
~~~

**Comment by astahlman** [comment]
Care to review? https://github.com/astahlman/ob-async/pull/24/files?w=1

**Comment by avkoval** [comment]
Absolutely amazing reaction to my issue, I was hoping but did not expected you to fix it so fast. Thank you, it worked well against my use-cases.

**Comment by astahlman** [comment]
Glad to hear it!
