### ISSUE TITLE
Output of stderr

### ISSUE THREAD

**Issue by GregorySchwartz** [astahlman/ob-async#41]
# Expected Behavior
With async enabled, output the error produced just like without async.

# Actual Behavior
Empty results with no errors.

# Steps to Reproduce
```
#+BEGIN_SRC sh :async
date -q
#+END_SRC
```
When run without async, produces error, with async, nothing produced.

**Comment by luveti** [comment]
Sorry to dig up an old issue, but I believe I'm experiencing the same problem. Is the org babel error buffer called " \*Org-Babel Error\*" showing up for you guys? Looking at the org babel source code would lead me to believe this buffer gets created in the child process you spin up.

I'm unsure if this would work, but maybe grabbing the contents of that buffer and returning it as a second return value could be a work around?
