### ISSUE TITLE
ob-async seems ignored :dir header argument

### ISSUE THREAD

**Issue by stardiviner** [astahlman/ob-async#44]
# Checklist
- [X] I followed the [troubleshooting guide](https://github.com/astahlman/ob-async#troubleshooting) and it did not address my issue
- [X] I've included a link to a Github Gist with the full contents of my `troubleshooting.org` buffer
- [X] Each section below is filled in and includes sufficient detail to reproduce the issue

# Expected Behavior
The source block should take advantage of `:dir` header argument.

# Actual Behavior
It seems missed it.

And it report error:

    executing Sh code block...
    Saving file /home/stardiviner/Org/Wiki/Computer Technology/Operating System/Linux/Command Line/Command Line.org...
    Wrote /home/stardiviner/Org/Wiki/Computer Technology/Operating System/Linux/Command Line/Command Line.org
    source-code block ‘12:16:53>’ not found in this buffer
    error in process sentinel: save-current-buffer: Opening output file: No such file or directory, /home/stardiviner/Org/Wiki/Computer Technology/Operating System/Linux/Command Line/the-art-of-command-line/README.md
    error in process sentinel: Opening output file: No such file or directory, /home/stardiviner/Org/Wiki/Computer Technology/Operating System/Linux/Command Line/the-art-of-command-line/README.md
    Mark set

# Steps to Reproduce
```org
#+begin_src sh :mkdirp yes :results file link :dir "Data/Books" :file "the-art-of-command-line/README.md" :async
if [ -d the-art-of-command-line ]; then
  cd the-art-of-command-line ; git pull
else
  git clone --recursive https://github.com/jlevy/the-art-of-command-line.git the-art-of-command-line
fi
#+end_src

Without the ~:async~, it works fine.
```

# Troubleshooting Artifacts

https://gist.github.com/stardiviner/28d9dd594a4de2fa726277c279760387

**Comment by astahlman** [comment]
Thanks for reporting- I've just opened https://github.com/astahlman/ob-async/pull/45 with a fix. Can you review and confirm that the fix works?

**Comment by stardiviner** [comment]
I review the code, and test on the branch. It works fine. Thanks for quick patch. You're awesome.
