### ISSUE TITLE
The :async keyword doesn't seem to work

### ISSUE THREAD

**Issue by stsquad** [astahlman/ob-async#5]
According to the documentation I should be able to async-ify the execution of org-babel blocks by adding the :async keyword. This doesn't seem to work when I C-c C-c blocks, only if I manually call M-x ob-async-org-babel-execute-src-block.

Looking at the code I can see there is an alias but I'm not sure what the magic for overriding based on keywords is meant to do.

**Comment by astahlman** [comment]
Have you added the ctrl-c ctrl-c hook as described in the README?

`(add-to-list 'org-ctrl-c-ctrl-c-hook 'ob-async-org-babel-execute-src-block)`

**Comment by stsquad** [comment]
*doh* my bad. I did try searching for :async through the org files but missed the setup on the front page. I was obviously entranced by the animated gif ;-)
