### ISSUE TITLE
error in process sentinel: Cannot open load file: No such file or directory, org-version.el

### ISSUE THREAD

**Issue by alinbxSorcerer** [astahlman/ob-async#59]
I installed from melpa in doom.emacs,  with 
    (package! ob-async) in package.el
and (require `ob-async) in config.el 

when run 
```
#+BEGIN_SRC shell  :async
ls /
#+END_SRC

#+RESULTS:
: 5c2fdbddee3db775041e18d58df9ae2f
```

and report error message 

```
executing Shell code block...
error in process sentinel: async-handle-result: Cannot open load file: No such file or directory, org-version.el
error in process sentinel: Cannot open load file: No such file or directory, org-version.el
```
Emacs 26.3  
Kubuntu 19.10

**Comment by astahlman** [comment]
I'm not a doom user and wasn't able to reproduce. Seems like this might have been resolved in https://github.com/hlissner/doom-emacs/issues/2010?

I'm going to close assuming the answer is "yes." If not, feel free to reopen with your [troubleshooting.org](https://github.com/astahlman/ob-async/blob/master/troubleshooting.org) attached and I can take a look.
