### ISSUE TITLE
error in process sentinel: async-handle-result: Symbol’s function definition is void: org-babel-get-header

### ISSUE THREAD

**Issue by ReichKV** [astahlman/ob-async#6]
Hi,
I tried to run the code from your gif-presentation. It failed with the following error:

error in process sentinel: async-handle-result: Symbol’s function definition is void: org-babel-get-header

Could you help me to solve this problem.

**Comment by astahlman** [comment]
`org-babel-get-header` was [removed](http://orgmode.org/Changes.html) in org 9. Do you have org 8 on your `load-path`?

**Comment by ReichKV** [comment]
Ok, i see. Indeed i use org-mode 9.  I do not know how to load org 8 and i am afraid it starts to interfere with org 9.

**Comment by astahlman** [comment]
No, you should be using org 9. I'm saying I think that org 8 is somehow getting pulled in on your `load-path`. ob-async works by launching a second Emacs process to execute your src block. Judging from that error message, there's some inconsistency between the version of org that you normally use and the version that's getting picked up in the second Emacs process.

You can try turning on async-debug [1] to see the elisp that's getting sent to the second Emacs process, then execute that code in a clean emacs session (via `emacs -Q`) and see what version of org it's using.

[1] `(setq async-debug t)`

**Comment by ReichKV** [comment]
Ah, I see thank you. Ok, i will try to solve problem with loading correct version of org.

**Comment by astahlman** [comment]
I've just added an interactive [troubleshooting guide](https://github.com/astahlman/ob-async/blob/master/troubleshooting.org) which may help. Closing this one, but feel free to reopen another issue if you are still facing the problem after going through the guide.
