### ISSUE TITLE
Can't find ob-shell?

### ISSUE THREAD

**Issue by nyamada** [astahlman/ob-async#7]
I'm sure it's probably a problem with my config --

Installed ob-async via Melpa. I've turned on debugging, but every time I try to run a SQL code block with the :async header I get the following problems:

` executing
 Sql code block...
 Transmitting sexp {{{'(lambda nil
    (setq exec-path
          '("/usr/local/opt/pyenv/shims" "/usr/local/pgsql/9.6/bin" "/Applications/Racket v6.2.1/bin"  "/usr/local/sbin" "/usr/local/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/opt/X11/bin"  "/usr/texbin" "/Users/parataxis/.pyenv/shims" "/Applications/Racket v6.2.1/bin" "/usr/local/sbin" "/opt/local/bin" "/Users/parataxis/.local/bin" "/usr/local/texlive/2013/bin/x86_64-darwin" "/opt/local/bin" "/Users/parataxis/.local/bin" "." "/usr/local/texlive/2013/bin/x86_64-darwin" "/usr/local/opt/go/libexec/bin" "/usr/local/Cellar/emacs/HEAD/libexec/emacs/25.1.50/x86_64-apple-darwin15.5.0" "/usr/local/bin"))
   (package-initialize)
   (org-babel-do-load-languages 'org-babel-load-languages
                                '((python . t)
                                  (perl . t)
                                  (R . t)
                                  (sql . t)
                                  (shell . t)
                                  (lilypond . t)
                                  (restclient . t)
                                  (gnuplot . t)
                                  (R . t)
                                  (ditaa . t)))
   (org-babel-execute:sql "SELECT *\nFROM foo"
                          '((:colname-names)
                            (:rowname-names)
                            (:result-params "replace")
                            (:result-type . value)
                            (:results . "replace")
                            (:exports . "code")
                            (:session . "none")
                            (:cache . "no")
                            (:noweb . "no")
                            (:hlines . "no")
                            (:tangle . "no")
                            (:dir . "/wk_linode:/home/nyamada")
                            (:dbhost . "seo-reports.ziprecruiter.com")
                            (:engine . "postgresql")
                            (:dbuser . "seo_admin")
                            (:database . "seo_reports")
                            (:cmdline . "-X")
                            (:async))))
}}}
 error in process sentinel: async-handle-result: Cannot open load file: No such file or directory,  ob-shell
 error in process sentinel: Cannot open load file: No such file or directory, ob-shell
 Quit
 Auto-saving...done
 Mark set
`

I've got ob-shell enabled and it works in the parent process.

**Comment by nyamada** [comment]
closing issue --

The issue is that my  org-babel-do-load-languages stanza used to have (shell . t). But apparently the new way to do this is (sh . t)
 
I've got a different issue now, but this one is moot.

**Comment by vxe** [comment]
did you find a solution for this?  having a similar problem

**Comment by paulrd** [comment]
I'm having the same issue in spacemacs develop version. I don't want to customize org-babel-load-languages as this variable is customized internally by the various language layers and I don't want to risk overwriting this when / if I add new language layers.
