### ISSUE TITLE
Can't exec ob-async due to `error in process sentinel: async-handle-result: Invalid read syntax: "#"`

### ISSUE THREAD

**Issue by adamist521** [astahlman/ob-async#75]
# Checklist
- [x] I followed the [troubleshooting guide](https://github.com/astahlman/ob-async#troubleshooting) and it did not address my issue
- [x] I've included a link to a Github Gist with the full contents of my `troubleshooting.org` buffer
- [x] Each section below is filled in and includes sufficient detail to reproduce the issue

# Expected Behavior

`#+RESULTS` in buffer should change to actual result.

# Actual Behavior
`#+RESULTS` in buffer changes to token but does not change to actual result after that.
ex. 
```
#+RESULTS:
: 2d182a9f90d63cded606c28e8182894c
```

# Steps to Reproduce
All `:async` is not working now...

# Troubleshooting Artifacts

- `emacs-async` should be working. (from gist)
- Error message returned in Message buffer is following
```
error in process sentinel: async-handle-result: Invalid read syntax: "#"
error in process sentinel: Invalid read syntax: "#"
```

[troubleshooting.org gist](https://gist.githubusercontent.com/adamist521/2818db8588279cae73eff4e337ba812e/raw/a1797507497e80dc4af7663c0fcb645f0abb5bd7/troubleshooting.org)

**Comment by adamist521** [comment]
It should be same as following link but made it to new issue since it seems to be different issue
https://github.com/astahlman/ob-async/issues/73#issuecomment-760647359

**Comment by adamist521** [comment]
listing issue that could be related

(I thought it was issue on `async` but `async` worked on `troubleshooting.org` so I judged it was issue on `ob-sync` )
https://github.com/jwiegley/emacs-async/issues/52
https://github.com/jwiegley/emacs-async/issues/22

**Comment by adamist521** [comment]
updated `ob-sync` to latest (github master) and solved issue.

following is doom-emacs setting
```
(package! ob-async
  :recipe (:host github :repo "astahlman/ob-async"))
```

```
(add-hook 'ob-async-pre-execute-src-block-hook
          '(lambda ()
             (setq org-plantuml-jar-path "~/plantuml.jar")))
```

**Comment by moritzptm** [comment]
I had the same error here. When enabling the debugging in the `async` package, found that it was an error in setq in the code sent to the background emacs process. In my case, the following code fails: 
```lisp
(setq org-babel-hide-result-overlays (#<overlay from 79 to 79>))
```
Is happens when the `#+RESULTS` drawer is collapsed. I didn't dig deep in the code, but worked around just setting the value to nil when calling the execute.

```lisp
(defun no-hide-overlays (orig-fun &rest args)
  (setq org-babel-hide-result-overlays nil))

(advice-add 'ob-async-org-babel-execute-src-block :before #'no-hide-overlays)
```
